edition = "2021"
max_width = 100

use_try_shorthand = true

format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"

reorder_modules = true
indent_style = "Block"
imports_layout = "HorizontalVertical"
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"

reorder_impl_items = true

match_arm_leading_pipes = "Always"
match_block_trailing_comma =  true

wrap_comments = true
comment_width = 92
format_code_in_doc_comments = true


# Align ='s in enums
enum_discrim_align_threshold = 100
struct_field_align_threshold = 100
