static INSTRUCTIONS_PREDICATE: [Instruction; 24] = [
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o270,
        name: "eq",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o274,
        name: "eq-no-pop",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o263,
        name: "eql",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o267,
        name: "eql-no-pop",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o260,
        name: "equal-number",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o264,
        name: "equal-number-no-pop",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o262,
        name: "greaterp",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o266,
        name: "greaterp-no-pop",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o261,
        name: "lessp",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o265,
        name: "lessp-no-pop",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o273,
        name: "logtest",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o277,
        name: "logtest-no-pop",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o040,
        name: "type-member-1",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o041,
        name: "type-member-2",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o042,
        name: "type-member-3",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o043,
        name: "type-member-4",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o044,
        name: "type-member-1-no-pop",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o045,
        name: "type-member-2-no-pop",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o046,
        name: "type-member-3-no-pop",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o047,
        name: "type-member-4-no-pop",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o002,
        name: "endp",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o036,
        name: "plusp",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o035,
        name: "minusp",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::PREDICATE,
        opcode: 0o034,
        name: "zerop",
        is_implemented: false,
    },
];
