static INSTRUCTIONS_NUMERIC: [Instruction; 24] = [
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o300,
        name: "add",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o301,
        name: "sub",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o114,
        name: "unary-minus",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o148,
        name: "increment",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o144,
        name: "decrement",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o202,
        name: "multiply",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o203,
        name: "quotient",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o204,
        name: "ceiling",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o205,
        name: "floor",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o206,
        name: "truncate",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o207,
        name: "round",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o210,
        name: "remainder",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o211,
        name: "rational-quotient",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o212,
        name: "min",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o213,
        name: "max",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o215,
        name: "logand",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o216,
        name: "logxor",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o217,
        name: "logior",
        is_implemented: false,
    },
    Instruction {
        family: InstructionFamily::NUMERIC,
        opcode: 0o232,
        name: "ash",
        is_implemented: false,
    },
];
