use crate::common::constants::OpCode;
use crate::hardware::machine::VirtualMachine;

use super::common::{ Instruction, InstructionFamily, InstructionFormat };

pub fn make_instructions_lexical_variable() -> Vec<Instruction> {
    return vec![
        Instruction::new()
            .set_name("push-lexical-var-0".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PushLexicalVar0)
            .set_exec(Some(VirtualMachine::cpu_push_lexical_var_0)),
        Instruction::new()
            .set_name("push-lexical-var-1".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PushLexicalVar1)
            .set_exec(Some(VirtualMachine::cpu_push_lexical_var_1)),
        Instruction::new()
            .set_name("push-lexical-var-2".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PushLexicalVar2)
            .set_exec(Some(VirtualMachine::cpu_push_lexical_var_2)),
        Instruction::new()
            .set_name("push-lexical-var-3".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PushLexicalVar3)
            .set_exec(Some(VirtualMachine::cpu_push_lexical_var_3)),
        Instruction::new()
            .set_name("push-lexical-var-4".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PushLexicalVar4)
            .set_exec(Some(VirtualMachine::cpu_push_lexical_var_4)),
        Instruction::new()
            .set_name("push-lexical-var-5".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PushLexicalVar5)
            .set_exec(Some(VirtualMachine::cpu_push_lexical_var_5)),
        Instruction::new()
            .set_name("push-lexical-var-6".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PushLexicalVar6)
            .set_exec(Some(VirtualMachine::cpu_push_lexical_var_6)),
        Instruction::new()
            .set_name("push-lexical-var-7".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PushLexicalVar7)
            .set_exec(Some(VirtualMachine::cpu_push_lexical_var_7)),
        Instruction::new()
            .set_name("pop-lexical-var-0".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PopLexicalVar0)
            .set_exec(Some(VirtualMachine::cpu_pop_lexical_var_0)),
        Instruction::new()
            .set_name("pop-lexical-var-1".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PopLexicalVar1)
            .set_exec(Some(VirtualMachine::cpu_pop_lexical_var_1)),
        Instruction::new()
            .set_name("pop-lexical-var-2".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PopLexicalVar2)
            .set_exec(Some(VirtualMachine::cpu_pop_lexical_var_2)),
        Instruction::new()
            .set_name("pop-lexical-var-3".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PopLexicalVar3)
            .set_exec(Some(VirtualMachine::cpu_pop_lexical_var_3)),
        Instruction::new()
            .set_name("pop-lexical-var-4".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PopLexicalVar4)
            .set_exec(Some(VirtualMachine::cpu_pop_lexical_var_4)),
        Instruction::new()
            .set_name("pop-lexical-var-5".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PopLexicalVar5)
            .set_exec(Some(VirtualMachine::cpu_pop_lexical_var_5)),
        Instruction::new()
            .set_name("pop-lexical-var-6".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PopLexicalVar6)
            .set_exec(Some(VirtualMachine::cpu_pop_lexical_var_6)),
        Instruction::new()
            .set_name("pop-lexical-var-7".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::PopLexicalVar7)
            .set_exec(Some(VirtualMachine::cpu_pop_lexical_var_7)),
        Instruction::new()
            .set_name("movem-lexical-var-0".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::MovemLexicalVar0)
            .set_exec(Some(VirtualMachine::cpu_movem_lexical_var_0)),
        Instruction::new()
            .set_name("movem-lexical-var-1".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::MovemLexicalVar1)
            .set_exec(Some(VirtualMachine::cpu_movem_lexical_var_1)),
        Instruction::new()
            .set_name("movem-lexical-var-2".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::MovemLexicalVar2)
            .set_exec(Some(VirtualMachine::cpu_movem_lexical_var_2)),
        Instruction::new()
            .set_name("movem-lexical-var-3".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::MovemLexicalVar3)
            .set_exec(Some(VirtualMachine::cpu_movem_lexical_var_3)),
        Instruction::new()
            .set_name("movem-lexical-var-4".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::MovemLexicalVar4)
            .set_exec(Some(VirtualMachine::cpu_movem_lexical_var_4)),
        Instruction::new()
            .set_name("movem-lexical-var-5".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::MovemLexicalVar5)
            .set_exec(Some(VirtualMachine::cpu_movem_lexical_var_5)),
        Instruction::new()
            .set_name("movem-lexical-var-6".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::MovemLexicalVar6)
            .set_exec(Some(VirtualMachine::cpu_movem_lexical_var_6)),
        Instruction::new()
            .set_name("movem-lexical-var-7".to_string())
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(OpCode::MovemLexicalVar7)
            .set_exec(Some(VirtualMachine::cpu_movem_lexical_var_7))
    ];
}
