use crate::hardware::machine::VirtualMachine;

use super::common::{ Instruction, InstructionFamily, InstructionFormat };

pub fn make_instructions_instance_variable() -> Vec<Instruction> {
    return vec![
        Instruction::new()
            .set_name("push-instance-variable".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStackImmediate)
            .set_opcode(0o110)
            .set_exec(Some(VirtualMachine::cpu_push_instance_variable)),
        Instruction::new()
            .set_name("pop-instance-variable".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStackImmediate)
            .set_opcode(0o320)
            .set_exec(Some(VirtualMachine::cpu_pop_instance_variable)),
        Instruction::new()
            .set_name("movem-instance-variable".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStackImmediate)
            .set_opcode(0o321)
            .set_exec(Some(VirtualMachine::cpu_movem_instance_variable)),
        Instruction::new()
            .set_name("push-address-instance-variable".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStackImmediate)
            .set_opcode(0o111)
            .set_exec(Some(VirtualMachine::cpu_push_address_instance_variable)),
        Instruction::new()
            .set_name("push-instance-variable-ordered".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStackImmediate)
            .set_opcode(0o112)
            .set_exec(Some(VirtualMachine::cpu_push_address_instance_variable_ordered)),
        Instruction::new()
            .set_name("pop-instance-variable-ordered".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStackImmediate)
            .set_opcode(0o322)
            .set_exec(Some(VirtualMachine::cpu_pop_instance_variable_ordered)),
        Instruction::new()
            .set_name("movem-instance-variable-ordered".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStackImmediate)
            .set_opcode(0o323)
            .set_exec(Some(VirtualMachine::cpu_movem_instance_variable_ordered)),
        Instruction::new()
            .set_name("push-address-instance-variable-ordered".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStackImmediate)
            .set_opcode(0o113)
            .set_exec(Some(VirtualMachine::cpu_push_address_instance_variable_ordered)),
        Instruction::new()
            .set_name("%instance-ref".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o324)
            .set_exec(Some(VirtualMachine::cpu_instance_ref)),
        Instruction::new()
            .set_name("%instance-set".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o325)
            .set_exec(Some(VirtualMachine::cpu_instance_set)),
        Instruction::new()
            .set_name("%instance-loc".to_string())
            .set_family(InstructionFamily::InstanceVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o326)
            .set_exec(Some(VirtualMachine::cpu_instance_loc))
    ];
}
