use super::common::{ Instruction, InstructionFamily, InstructionFormat };

pub fn make_instructions_data_movement() -> Vec<Instruction> {
    return vec![
        Instruction::new()
            .set_name("push".to_string())
            .set_family(InstructionFamily::Interruptible)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o100),
        Instruction::new()
            .set_name("pop".to_string())
            .set_family(InstructionFamily::Interruptible)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o340),
        Instruction::new()
            .set_name("movem".to_string())
            .set_family(InstructionFamily::Interruptible)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o341),
        Instruction::new()
            .set_name("push-n-nils".to_string())
            .set_family(InstructionFamily::Interruptible)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o101),
        Instruction::new()
            .set_name("push-address".to_string())
            .set_family(InstructionFamily::Interruptible)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o150),
        Instruction::new()
            .set_name("set-sp-to-address".to_string())
            .set_family(InstructionFamily::Interruptible)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o151),
        Instruction::new()
            .set_name("set-sp-to-address-save-tos".to_string())
            .set_family(InstructionFamily::Interruptible)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o152),
        Instruction::new()
            .set_name("push-address-sp-relative".to_string())
            .set_family(InstructionFamily::Interruptible)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o102),
        Instruction::new()
            .set_name("stack-blt".to_string())
            .set_family(InstructionFamily::Interruptible)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o224),
        Instruction::new()
            .set_name("stack-blt-address".to_string())
            .set_family(InstructionFamily::Interruptible)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o352)
    ];
}
