use super::common::{ Instruction, InstructionFamily };

pub fn make_instructions_lexical_variable() -> Vec<Instruction<'static>> {
    return vec![
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o020)
            .set_name("push-lexical-var-0"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o021)
            .set_name("push-lexical-var-1"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o022)
            .set_name("push-lexical-var-2"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o023)
            .set_name("push-lexical-var-3"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o024)
            .set_name("push-lexical-var-4"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o025)
            .set_name("push-lexical-var-5"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o026)
            .set_name("push-lexical-var-6"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o027)
            .set_name("push-lexical-var-7"),

        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o240)
            .set_name("pop-lexical-var-0"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o241)
            .set_name("pop-lexical-var-1"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o242)
            .set_name("pop-lexical-var-2"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o243)
            .set_name("pop-lexical-var-3"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o244)
            .set_name("pop-lexical-var-4"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o245)
            .set_name("pop-lexical-var-5"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o246)
            .set_name("pop-lexical-var-6"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o247)
            .set_name("pop-lexical-var-7"),

        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o250)
            .set_name("movem-lexical-var-0"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o251)
            .set_name("movem-lexical-var-1"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o252)
            .set_name("movem-lexical-var-2"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o253)
            .set_name("movem-lexical-var-3"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o254)
            .set_name("movem-lexical-var-4"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o255)
            .set_name("movem-lexical-var-5"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o256)
            .set_name("movem-lexical-var-6"),
        Instruction::new()
            .set_family(InstructionFamily::LIST)
            .set_opcode(0o257)
            .set_name("movem-lexical-var-7")
    ];
}
