use super::common::{ Instruction, InstructionFamily, InstructionFormat };

pub fn make_instructions_lexical_variable() -> Vec<Instruction<'static>> {
    return vec![
        Instruction::new()
            .set_name("push-lexical-var-0")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o020),
        Instruction::new()
            .set_name("push-lexical-var-1")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o021),
        Instruction::new()
            .set_name("push-lexical-var-2")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o022),
        Instruction::new()
            .set_name("push-lexical-var-3")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o023),
        Instruction::new()
            .set_name("push-lexical-var-4")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o024),
        Instruction::new()
            .set_name("push-lexical-var-5")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o025),
        Instruction::new()
            .set_name("push-lexical-var-6")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o026),
        Instruction::new()
            .set_name("push-lexical-var-7")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o027),
        Instruction::new()
            .set_name("pop-lexical-var-0")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o240),
        Instruction::new()
            .set_name("pop-lexical-var-1")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o241),
        Instruction::new()
            .set_name("pop-lexical-var-2")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o242),
        Instruction::new()
            .set_name("pop-lexical-var-3")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o243),
        Instruction::new()
            .set_name("pop-lexical-var-4")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o244),
        Instruction::new()
            .set_name("pop-lexical-var-5")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o245),
        Instruction::new()
            .set_name("pop-lexical-var-6")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o246),
        Instruction::new()
            .set_name("pop-lexical-var-7")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o247),
        Instruction::new()
            .set_name("movem-lexical-var-0")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o250),
        Instruction::new()
            .set_name("movem-lexical-var-1")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o251),
        Instruction::new()
            .set_name("movem-lexical-var-2")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o252),
        Instruction::new()
            .set_name("movem-lexical-var-3")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o253),
        Instruction::new()
            .set_name("movem-lexical-var-4")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o254),
        Instruction::new()
            .set_name("movem-lexical-var-5")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o255),
        Instruction::new()
            .set_name("movem-lexical-var-6")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o256),
        Instruction::new()
            .set_name("movem-lexical-var-7")
            .set_family(InstructionFamily::LexicalVariableAccess)
            .set_format(InstructionFormat::OperandFromStack)
            .set_opcode(0o257)
    ];
}
